### ISSUE TITLE
Bad logic in GameSolver

### ISSUE THREAD

**Issue by jbrucker** [OOP2018/guessing-game-poorinp#4]
Your GameSolver must be able to solve anyone's game.
That means you must program it according the specification
of *how* a NumberGame behaves.
If you think this code is going to work, then please SHOW ME
where in the spec for GuessingGame does it say that the game 
must return "Right" when someone guesses the solution?

```java
	else if ( game.getMessage().contains("Right")) {
		break ;
	}
```

**Comment by ghost** [comment]
I already fixed that bad logic.
