### ISSUE TITLE
Github repo has wrong structure.

### ISSUE THREAD

**Issue by jbrucker** [OOP2018/guessing-game-poorinp#6]
You have a src/ directory and a ui/ directory.

ui/ should be inside the source directory.

src/ is your IDE project src/ directory, NOT the name of a package.

It should be:
```
src/NumberGame.java
    /YourGame.java
    /ui/ (your files for ui package)

All source code should be inside of src/.  
Please fix it before your code can be graded.

**Comment by ghost** [comment]
fixed it please check, thank you.
